# Generated by Django 4.1 on 2025-01-10 05:19

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Doctor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('specialization', models.CharField(max_length=50)),
                ('experience', models.IntegerField()),
                ('contact', models.BigIntegerField()),
            ],
        ),
    ]
