# Generated by Django 5.1.5 on 2025-01-21 15:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('doctorapp', '0004_registeration'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Doctor',
        ),
        migrations.RenameField(
            model_name='doctorprofile',
            old_name='address',
            new_name='city',
        ),
        migrations.RenameField(
            model_name='doctorprofile',
            old_name='phoneno',
            new_name='mobile',
        ),
        migrations.RenameField(
            model_name='doctorprofile',
            old_name='email',
            new_name='username',
        ),
        migrations.AddField(
            model_name='doctorprofile',
            name='password',
            field=models.CharField(default='exit', max_length=12),
            preserve_default=False,
        ),
    ]
